/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInfo {
  'name' : string,
  'role' : string,
  'email' : string,
  'phoneNumber' : string,
}
export interface Domain { 'name' : string, 'description' : string }
export interface EventInfo {
  'organizer' : string,
  'name' : string,
  'description' : string,
  'college' : string,
  'eventDate' : string,
}
export interface Registration {
  'domain' : string,
  'collegeName' : string,
  'email' : string,
  'teamMembers' : Array<string>,
  'projectTitle' : string,
  'abstract' : string,
  'sdgGoalNumber' : string,
  'department' : string,
  'phoneNumber' : string,
  'yearOfStudy' : string,
  'teamLeaderName' : string,
}
export interface TimelineStage { 'date' : string, 'stageName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContactInfo' : ActorMethod<[ContactInfo], string>,
  'addDomain' : ActorMethod<[string, string], string>,
  'addTimelineStage' : ActorMethod<[string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteContactInfo' : ActorMethod<[string], string>,
  'deleteDomain' : ActorMethod<[string], string>,
  'deleteTimelineStage' : ActorMethod<[string], string>,
  'getAllContacts' : ActorMethod<[], Array<ContactInfo>>,
  'getAllDomains' : ActorMethod<[], Array<Domain>>,
  'getAllRegistrations' : ActorMethod<[], Array<Registration>>,
  'getAllTimelineStages' : ActorMethod<[], Array<TimelineStage>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEventInfo' : ActorMethod<[], EventInfo>,
  'getRegistration' : ActorMethod<[string], Registration>,
  'getRegistrationCount' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerTeam' : ActorMethod<[Registration], string>,
  'updateContactInfo' : ActorMethod<[string, ContactInfo], string>,
  'updateDomain' : ActorMethod<[string, Domain], string>,
  'updateEventInfo' : ActorMethod<[EventInfo], string>,
  'updateTimelineStage' : ActorMethod<[string, TimelineStage], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];