/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactInfo = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Domain = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Registration = IDL.Record({
  'domain' : IDL.Text,
  'collegeName' : IDL.Text,
  'email' : IDL.Text,
  'teamMembers' : IDL.Vec(IDL.Text),
  'projectTitle' : IDL.Text,
  'abstract' : IDL.Text,
  'sdgGoalNumber' : IDL.Text,
  'department' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'yearOfStudy' : IDL.Text,
  'teamLeaderName' : IDL.Text,
});
export const TimelineStage = IDL.Record({
  'date' : IDL.Text,
  'stageName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const EventInfo = IDL.Record({
  'organizer' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'college' : IDL.Text,
  'eventDate' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContactInfo' : IDL.Func([ContactInfo], [IDL.Text], []),
  'addDomain' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'addTimelineStage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteContactInfo' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deleteDomain' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deleteTimelineStage' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllContacts' : IDL.Func([], [IDL.Vec(ContactInfo)], ['query']),
  'getAllDomains' : IDL.Func([], [IDL.Vec(Domain)], ['query']),
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getAllTimelineStages' : IDL.Func([], [IDL.Vec(TimelineStage)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEventInfo' : IDL.Func([], [EventInfo], ['query']),
  'getRegistration' : IDL.Func([IDL.Text], [Registration], ['query']),
  'getRegistrationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerTeam' : IDL.Func([Registration], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateContactInfo' : IDL.Func([IDL.Text, ContactInfo], [IDL.Text], []),
  'updateDomain' : IDL.Func([IDL.Text, Domain], [IDL.Text], []),
  'updateEventInfo' : IDL.Func([EventInfo], [IDL.Text], []),
  'updateTimelineStage' : IDL.Func([IDL.Text, TimelineStage], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactInfo = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Domain = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const Registration = IDL.Record({
    'domain' : IDL.Text,
    'collegeName' : IDL.Text,
    'email' : IDL.Text,
    'teamMembers' : IDL.Vec(IDL.Text),
    'projectTitle' : IDL.Text,
    'abstract' : IDL.Text,
    'sdgGoalNumber' : IDL.Text,
    'department' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'yearOfStudy' : IDL.Text,
    'teamLeaderName' : IDL.Text,
  });
  const TimelineStage = IDL.Record({
    'date' : IDL.Text,
    'stageName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const EventInfo = IDL.Record({
    'organizer' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'college' : IDL.Text,
    'eventDate' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContactInfo' : IDL.Func([ContactInfo], [IDL.Text], []),
    'addDomain' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'addTimelineStage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteContactInfo' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deleteDomain' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deleteTimelineStage' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllContacts' : IDL.Func([], [IDL.Vec(ContactInfo)], ['query']),
    'getAllDomains' : IDL.Func([], [IDL.Vec(Domain)], ['query']),
    'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getAllTimelineStages' : IDL.Func([], [IDL.Vec(TimelineStage)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEventInfo' : IDL.Func([], [EventInfo], ['query']),
    'getRegistration' : IDL.Func([IDL.Text], [Registration], ['query']),
    'getRegistrationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerTeam' : IDL.Func([Registration], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateContactInfo' : IDL.Func([IDL.Text, ContactInfo], [IDL.Text], []),
    'updateDomain' : IDL.Func([IDL.Text, Domain], [IDL.Text], []),
    'updateEventInfo' : IDL.Func([EventInfo], [IDL.Text], []),
    'updateTimelineStage' : IDL.Func([IDL.Text, TimelineStage], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };